export interface DisclosureOptions {
  listingAddress?: string;
  mlsNumber?: string;
  agentName?: string;
  brokerageName?: string;
  enhancementTypes: string[];
  enhancementDate: string;
}

/**
 * Generate MLS-compliant disclosure text
 */
export function generateDisclosure(options: DisclosureOptions): string {
  const {
    listingAddress = '[Property Address]',
    mlsNumber,
    agentName,
    brokerageName,
    enhancementTypes,
    enhancementDate,
  } = options;

  const enhancementList = enhancementTypes.map(type => {
    const labels: Record<string, string> = {
      'VirtualStaging': 'Virtual Staging',
      'ObjectRemoval': 'Digital Object Removal',
      'SkyReplacement': 'Sky Replacement',
      'VirtualTwilight': 'Virtual Twilight Conversion',
      'LandscapeEnhancement': 'Digital Landscape Enhancement',
      'DigitalEnhancement': 'Digital Enhancement',
      'LightingEnhancement': 'Digital Lighting Enhancement',
      'HDRProcessing': 'HDR Processing',
      'AutoEnhancement': 'Auto Enhancement',
    };
    return labels[type] || type;
  }).join(', ');

  const date = new Date(enhancementDate).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `
PHOTO ENHANCEMENT DISCLOSURE

Property: ${listingAddress}
${mlsNumber ? `MLS #: ${mlsNumber}` : ''}
${agentName ? `Listing Agent: ${agentName}` : ''}
${brokerageName ? `Brokerage: ${brokerageName}` : ''}

NOTICE: One or more photographs in this listing have been digitally enhanced 
using the following techniques:

- ${enhancementList}

Enhancement Date: ${date}
Enhancement Provider: SnapR (snap-r.com)

These enhancements are for illustrative purposes only. The digitally enhanced 
images may not represent the actual current condition of the property. 
Virtually staged images show furniture and décor that are NOT included with 
the property. Buyers are encouraged to visit the property in person to verify 
its actual condition and features.

This disclosure is provided in compliance with NAR Code of Ethics Article 12 
and applicable MLS rules regarding digital alterations to listing photographs.

---
Generated by SnapR | snap-r.com
`.trim();
}

/**
 * Generate short disclosure for MLS photo captions
 */
export function generateShortDisclosure(toolId: string): string {
  const disclosures: Record<string, string> = {
    'virtual-staging': 'Virtually Staged - Furniture Not Included',
    'item-removal': 'Digitally Edited - Items Removed',
    'declutter': 'Digitally Edited - Items Removed',
    'sky-replacement': 'Sky Digitally Enhanced',
    'virtual-twilight': 'Digitally Converted to Twilight',
    'fire-in-fireplace': 'Digitally Enhanced',
    'tv-screen-replacement': 'Digitally Enhanced',
    'art-wall-replacement': 'Digitally Enhanced',
  };
  return disclosures[toolId] || 'Digitally Enhanced';
}

/**
 * Generate photo description for MLS upload
 */
export function generatePhotoDescription(
  toolId: string,
  roomType?: string,
  photoNumber?: number
): string {
  const roomLabel = roomType ? ` - ${roomType}` : '';
  const photoLabel = photoNumber ? ` (Photo ${photoNumber})` : '';
  const disclosure = generateShortDisclosure(toolId);
  
  return `${disclosure}${roomLabel}${photoLabel}`;
}
