language: en
reviews:
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "app/api/**"
      instructions: "Check for authentication, authorization, input validation, and secure use of environment variables"
    - path: "lib/**"
      instructions: "Check for security issues and proper error handling"
chat:
  auto_reply: true
