# CodeRabbit Configuration for SnapR
# Real Estate Photo Enhancement Platform
# Next.js + Supabase + AI APIs

language: en-US

early_access: true

reviews:
  # Enable automatic reviews on all PRs
  auto_review:
    enabled: true
    drafts: false  # Don't review draft PRs
    base_branches:
      - main
      - develop
  
  # Review profile - thorough but not overwhelming
  profile: chill  # Options: chill, assertive, default
  
  # What to focus on
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false  # Skip the poem, we're serious here
  review_status: true
  collapse_walkthrough: false
  
  # Path-based instructions
  path_instructions:
    - path: "app/api/**"
      instructions: |
        Focus on:
        - API security (auth checks, input validation)
        - Error handling and proper status codes
        - Rate limiting considerations
        - Supabase RLS compliance
        - Cost tracking for AI API calls (OpenAI, Replicate, Runware)
    
    - path: "app/dashboard/**"
      instructions: |
        Focus on:
        - User authentication checks
        - Loading states and error boundaries
        - Mobile responsiveness
        - Accessibility (a11y)
    
    - path: "components/**"
      instructions: |
        Focus on:
        - Reusability and prop types
        - Performance (unnecessary re-renders)
        - Accessibility
        - Consistent styling with Tailwind
    
    - path: "lib/supabase/**"
      instructions: |
        Focus on:
        - Proper error handling
        - RLS policy compliance
        - Connection management
        - Type safety
    
    - path: "**/*.tsx"
      instructions: |
        Check for:
        - TypeScript strict mode compliance
        - Proper null/undefined handling
        - React hooks best practices
        - Memory leaks (useEffect cleanup)

# Chat with CodeRabbit in PR comments
chat:
  auto_reply: true

# Ignore certain files/paths
path_filters:
  - "!**/*.min.js"
  - "!**/*.min.css"
  - "!**/node_modules/**"
  - "!**/.next/**"
  - "!**/dist/**"
  - "!**/*.lock"
  - "!**/package-lock.json"
  - "!**/*.svg"
  - "!**/*.ico"
  - "!**/*.png"
  - "!**/*.jpg"
  - "!**/*.webp"

# Knowledge base - help CodeRabbit understand your codebase
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  pull_requests:
    scope: auto

# Custom review rules for SnapR
tools:
  # Static analysis
  eslint:
    enabled: true
  
  # Biome (if you use it)
  biome:
    enabled: false
  
  # GitHub Actions
  github_actions:
    enabled: true
  
  # Security scanning
  ast_grep:
    enabled: true
    packages:
      - "@anthropic-ai/ast-grep-essentials"

# Tone and style
tone_instructions: |
  Be concise and actionable. SnapR is a fast-moving startup building a real estate photo enhancement platform.
  
  Key context:
  - We use Next.js 14+ with App Router
  - Supabase for auth, database, and storage
  - Multiple AI providers: OpenAI, Replicate, Runware
  - Stripe for payments
  - Premium gold/black design theme
  
  Priorities:
  1. Security (especially auth, payments, user data)
  2. Performance (AI operations can be slow/expensive)
  3. Cost efficiency (track AI API usage)
  4. User experience (real estate professionals are busy)
  
  Don't be pedantic about minor style issues. Focus on bugs, security, and performance.
