'use client'
import { forwardRef } from 'react'

interface PropertyData { address?: string; city?: string; state?: string; price?: number; bedrooms?: number; bathrooms?: number; squareFeet?: number }
interface BrandData { business_name?: string; logo_url?: string; primary_color?: string; secondary_color?: string; phone?: string }
interface Props { templateId: string; photoUrl: string; property: PropertyData; brand: BrandData; headline?: string }

function formatPrice(price: number): string {
  if (price >= 1000000) return `$${(price / 1000000).toFixed(price % 1000000 === 0 ? 0 : 1)}M`
  if (price >= 1000) return `$${(price / 1000).toFixed(0)}K`
  return `$${price.toLocaleString()}`
}

export const FacebookTemplateRenderer = forwardRef<HTMLDivElement, Props>(
  ({ templateId, photoUrl, property, brand, headline = 'JUST LISTED' }, ref) => {
    const pc = brand.primary_color || '#D4AF37'
    const sc = brand.secondary_color || '#1A1A1A'
    const p = property
    const b = brand
    const isCS = templateId?.includes('cs-')
    const isOH = templateId?.includes('oh-')
    const isPR = templateId?.includes('pr-')
    const isUC = templateId?.includes('uc-')
    const isJS = templateId?.includes('js-')

    if (isCS) {
      if (templateId?.includes('blur')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" style={{ filter: 'blur(15px)' }} crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-2xl mb-2">👀</div><div className="text-5xl font-bold mb-4">COMING SOON</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-xl text-white/70">{p.city}, {p.state}</div><div className="text-4xl font-bold mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('exclusive')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute top-6 right-6 px-4 py-2 rounded-full" style={{ backgroundColor: pc }}><span className="font-bold" style={{ color: sc }}>EXCLUSIVE</span></div><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-sm tracking-widest mb-2 text-white/60">PRIVATE PREVIEW</div><div className="text-5xl font-light mb-4">COMING SOON</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-4xl mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('countdown')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" style={{ filter: 'blur(8px) brightness(0.5)' }} crossOrigin="anonymous" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white"><div className="text-lg tracking-widest mb-4" style={{ color: pc }}>LAUNCHING SOON</div><div className="flex gap-4 mb-6">{['03','12','45','22'].map((n,i)=>(<div key={i} className="text-center"><div className="w-16 h-16 rounded-xl flex items-center justify-center text-3xl font-bold" style={{backgroundColor:pc,color:sc}}>{n}</div><div className="text-xs mt-1 text-white/60">{['DAYS','HRS','MIN','SEC'][i]}</div></div>))}</div><div className="text-3xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div><div className="text-4xl font-bold mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('sneak')) return (<div ref={ref} className="relative overflow-hidden" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-y-0 left-0 w-1/2 bg-black flex items-center justify-end pr-10"><div className="text-right text-white"><div className="text-sm tracking-widest mb-2" style={{ color: pc }}>SNEAK PEEK</div><div className="text-4xl font-bold mb-4">COMING SOON</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-3xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div></div><div className="absolute bottom-4 left-4 text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('dark')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui', backgroundColor: '#0a0a0a' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover opacity-30" style={{ filter: 'grayscale(100%)' }} crossOrigin="anonymous" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-8xl font-thin mb-4">?</div><div className="text-4xl font-bold tracking-wider mb-4">COMING SOON</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-white/50">{p.city}, {p.state}</div><div className="text-3xl mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/40">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" style={{ filter: 'blur(5px)' }} crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/70 to-black/40" /><div className="absolute left-10 top-0 bottom-0 w-1/2 flex flex-col justify-center text-white"><div className="w-16 h-16 rounded-full flex items-center justify-center mb-4" style={{ backgroundColor: pc }}><span className="text-3xl">🔔</span></div><div className="text-4xl font-bold mb-2">COMING SOON</div><div className="text-white/70 mb-4">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div><div className="px-6 py-3 rounded-full inline-block w-fit font-bold" style={{ backgroundColor: pc, color: sc }}>GET NOTIFIED</div></div><div className="absolute bottom-4 left-10 text-white/60">{b.business_name} • {b.phone}</div></div>)
    }

    if (isOH) {
      if (templateId?.includes('invite')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-6 border border-white/30" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-sm tracking-widest mb-2 text-white/60">YOU ARE INVITED</div><div className="text-4xl font-light mb-4">OPEN HOUSE</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-4xl font-bold mb-2" style={{ color: pc }}>SAT & SUN</div><div className="text-xl mb-4">1:00 PM - 4:00 PM</div><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('calendar')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 to-transparent" /><div className="absolute top-6 right-6 w-32 bg-white rounded-xl overflow-hidden shadow-xl"><div className="py-2 text-center text-white font-bold" style={{ backgroundColor: pc }}>SAT</div><div className="py-4 text-center"><div className="text-4xl font-bold text-gray-900">15</div><div className="text-gray-500">1-4 PM</div></div></div><div className="absolute left-10 top-0 bottom-0 w-1/2 flex flex-col justify-center text-white"><div className="text-xl font-bold tracking-wider mb-2" style={{ color: pc }}>OPEN HOUSE</div><div className="text-3xl font-bold mb-2">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-4xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('welcome')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-black/40" /><div className="absolute top-6 left-1/2 transform -translate-x-1/2"><div className="px-6 py-3 rounded-full" style={{ backgroundColor: pc }}><span className="text-xl font-bold" style={{ color: sc }}>🚪 OPEN HOUSE</span></div></div><div className="absolute bottom-0 left-0 right-0 p-8 text-white text-center"><div className="text-4xl font-light mb-4">Welcome Home</div><div className="text-xl mb-1">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-3xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div></div>)
      if (templateId?.includes('weekend')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/40" /><div className="absolute top-0 left-0 right-0 py-4" style={{ backgroundColor: pc }}><div className="text-center text-2xl font-black" style={{ color: sc }}>🏠 WEEKEND OPEN HOUSE</div></div><div className="absolute bottom-0 left-0 right-0 p-6" style={{ backgroundColor: sc }}><div className="flex justify-between items-end text-white"><div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div><div className="text-right"><div className="text-3xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div>SAT & SUN • 1PM - 4PM</div></div></div></div></div>)
      if (templateId?.includes('luxury')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-6 border" style={{ borderColor: pc }} /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-sm tracking-widest mb-2" style={{ color: pc }}>EXCLUSIVE VIEWING</div><div className="text-4xl font-light mb-6">OPEN HOUSE</div><div className="text-3xl font-bold mb-2" style={{ color: pc }}>SAT 15 • 2-5 PM</div><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 to-transparent" /><div className="absolute left-10 top-0 bottom-0 w-1/2 flex flex-col justify-center text-white"><div className="text-xl tracking-wider mb-2" style={{ color: pc }}>OPEN HOUSE</div><div className="text-3xl font-bold mb-4">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div><div className="px-6 py-3 rounded-full inline-block w-fit font-bold" style={{ backgroundColor: pc, color: sc }}>RSVP NOW</div></div><div className="absolute bottom-4 left-10 text-white/60">{b.business_name} • {b.phone}</div></div>)
    }

    if (isPR) {
      if (templateId?.includes('strike')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/60 to-transparent" /><div className="absolute top-6 left-6 px-4 py-2" style={{ backgroundColor: '#DC2626' }}><span className="text-white font-bold">🔥 PRICE REDUCED</span></div><div className="absolute left-10 top-20 bottom-10 w-1/2 flex flex-col justify-center text-white"><div className="text-2xl text-white/50 line-through mb-2">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-5xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('savings')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute top-6 right-6 w-32 h-32 rounded-full flex flex-col items-center justify-center" style={{ backgroundColor: '#DC2626' }}><div className="text-white text-sm">SAVE</div><div className="text-white text-2xl font-black">{formatPrice((p.price || 0) * 0.1)}</div></div><div className="absolute bottom-0 left-0 right-0 p-8 text-white"><div className="text-xl text-white/50 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-5xl font-bold mb-2" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('new')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><div className="absolute inset-0 grid grid-cols-2"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /><div className="bg-white p-8 flex flex-col justify-center"><div className="flex items-center gap-3 mb-4"><span className="px-3 py-1 bg-green-500 text-white font-bold rounded">NEW PRICE</span><span className="text-gray-400 line-through text-xl">{formatPrice((p.price || 0) * 1.1)}</span></div><div className="text-5xl font-bold text-gray-900 mb-4">{formatPrice(p.price || 0)}</div><div className="text-xl text-gray-700">{p.address}</div><div className="text-gray-500 mb-4">{p.city}, {p.state}</div><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold" style={{ backgroundColor: pc }}>{b.business_name?.[0]}</div><div><div className="font-semibold text-gray-900">{b.business_name}</div><div className="text-gray-500 text-sm">{b.phone}</div></div></div></div></div></div>)
      if (templateId?.includes('opportunity')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-sm tracking-widest mb-2" style={{ color: pc }}>RARE OPPORTUNITY</div><div className="text-4xl font-light mb-6">PRICE IMPROVED</div><div className="text-xl text-white/50 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-5xl font-light mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('motivated')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 to-transparent" /><div className="absolute top-6 left-6 px-4 py-2 rounded" style={{ backgroundColor: '#DC2626' }}><span className="text-white font-bold">⚡ MOTIVATED SELLER</span></div><div className="absolute left-10 top-20 bottom-10 w-1/2 flex flex-col justify-center text-white"><div className="text-2xl text-white/40 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-5xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute top-0 left-0 right-0 py-4" style={{ backgroundColor: '#DC2626' }}><div className="text-center text-white text-2xl font-black">🚨 PRICE DROP ALERT 🚨</div></div><div className="absolute inset-0 pt-16 flex flex-col items-center justify-center text-white text-center"><div className="text-xl text-white/50 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-6xl font-black my-2" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
    }

    if (isUC) {
      if (templateId?.includes('pending')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/30" /><div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 -rotate-12"><div className="px-16 py-4" style={{ backgroundColor: pc }}><span className="text-4xl font-black" style={{ color: sc }}>📝 PENDING</span></div></div><div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black to-transparent text-white"><div className="flex justify-between items-end"><div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div><div className="text-right"><div className="text-3xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-white/70">{b.business_name} • {b.phone}</div></div></div></div></div>)
      if (templateId?.includes('accepted')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-6xl mb-4">🎉</div><div className="text-4xl font-light mb-4">OFFER ACCEPTED</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-3xl mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('fast')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 to-transparent" /><div className="absolute top-6 left-6 px-4 py-2 rounded-full" style={{ backgroundColor: '#DC2626' }}><span className="text-white font-bold">⚡ MOVING FAST</span></div><div className="absolute left-10 top-20 bottom-10 w-1/2 flex flex-col justify-center text-white"><div className="text-5xl font-black mb-2">UNDER CONTRACT</div><div className="text-lg text-white/60 mb-4">IN JUST 3 DAYS!</div><div className="text-2xl">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-4xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('check')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"><div className="w-32 h-32 rounded-full flex items-center justify-center" style={{ backgroundColor: '#22C55E' }}><span className="text-6xl text-white">✓</span></div></div><div className="absolute top-6 left-0 right-0 text-center text-3xl font-bold text-white">UNDER CONTRACT</div><div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black to-transparent text-white text-center"><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div><div className="mt-2">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('signed')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-6 border" style={{ borderColor: pc }} /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-sm tracking-widest mb-2 text-white/60">CONTRACT</div><div className="text-5xl font-light mb-4">SIGNED</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-3xl mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 to-black/30" /><div className="absolute top-6 left-6 px-4 py-2 rounded-full" style={{ backgroundColor: pc }}><span className="text-xl font-bold" style={{ color: sc }}>🏠 BUYERS FOUND!</span></div><div className="absolute bottom-0 left-0 right-0 p-8 text-white"><div className="text-3xl font-bold mb-2">New Homeowners!</div><div className="text-xl">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-3xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
    }

    if (isJS) {
      if (templateId?.includes('banner')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/30" /><div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 -rotate-12"><div className="px-16 py-4" style={{ backgroundColor: '#DC2626' }}><span className="text-5xl font-black text-white">🎉 SOLD!</span></div></div><div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black to-transparent text-white"><div className="flex justify-between items-end"><div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div><div className="text-right"><div className="text-3xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-white/70">{b.business_name} • {b.phone}</div></div></div></div></div>)
      if (templateId?.includes('celebrate')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-6xl mb-4">🎉</div><div className="text-5xl font-black mb-4">JUST SOLD!</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-4xl font-bold mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('gold')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-6 border-2" style={{ borderColor: pc }} /><div className="absolute top-10 left-1/2 transform -translate-x-1/2"><div className="px-8 py-2 rounded-full" style={{ backgroundColor: pc }}><span className="text-xl font-bold" style={{ color: sc }}>✨ SOLD ✨</span></div></div><div className="absolute inset-0 pt-20 flex flex-col items-center justify-center text-white text-center"><div className="text-4xl font-light mb-2">{p.address}</div><div className="text-white/60 mb-4">{p.city}, {p.state}</div><div className="text-5xl font-light" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('achieve')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 to-transparent" /><div className="absolute left-10 top-0 bottom-0 w-1/2 flex flex-col items-center justify-center text-white text-center"><div className="text-7xl mb-4">🏆</div><div className="text-2xl font-bold tracking-wider mb-2" style={{ color: pc }}>ANOTHER ONE</div><div className="text-5xl font-black mb-4">SOLD!</div><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-4xl font-bold mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-4 left-10 text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('record')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute top-0 left-0 right-0 py-3" style={{ backgroundColor: '#DC2626' }}><div className="text-center text-white text-xl font-bold">🔥 RECORD SALE 🔥</div></div><div className="absolute inset-0 pt-12 flex flex-col items-center justify-center text-white text-center"><div className="text-4xl font-black mb-2">JUST SOLD</div><div className="text-5xl font-black my-2" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><div className="absolute inset-0 grid grid-cols-2"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /><div className="bg-white p-8 flex flex-col justify-center"><div className="flex items-center gap-3 mb-4"><div className="px-3 py-1 rounded font-bold text-white" style={{ backgroundColor: '#22C55E' }}>SOLD</div><div className="text-3xl font-bold text-gray-900">{formatPrice(p.price || 0)}</div></div><div className="text-xl text-gray-700">{p.address}</div><div className="text-gray-500 mb-4">{p.city}, {p.state}</div><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold" style={{ backgroundColor: pc }}>{b.business_name?.[0]}</div><div><div className="font-semibold text-gray-900">{b.business_name}</div><div className="text-gray-500 text-sm">{b.phone}</div></div></div></div></div></div>)
    }

    // JUST LISTED styles
    if (templateId?.includes('luxury')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-6 border-2" style={{ borderColor: pc }} /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center"><div className="text-lg tracking-widest mb-2" style={{ color: pc }}>{headline}</div><div className="text-5xl font-light mb-4">{formatPrice(p.price || 0)}</div><div className="w-24 h-0.5 mb-4" style={{ backgroundColor: pc }} /><div className="text-2xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div className="absolute bottom-4 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
    if (templateId?.includes('minimal')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><div className="absolute inset-0 grid grid-cols-2"><div className="bg-white p-10 flex flex-col justify-between"><div><div className="text-sm tracking-widest mb-4" style={{ color: pc }}>{headline}</div><div className="text-4xl font-bold text-gray-900 mb-2">{formatPrice(p.price || 0)}</div><div className="text-xl text-gray-700">{p.address}</div><div className="text-gray-500">{p.city}, {p.state}</div></div><div><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full flex items-center justify-center text-white font-bold" style={{ backgroundColor: pc }}>{b.business_name?.[0]}</div><div><div className="font-semibold text-gray-900">{b.business_name}</div><div className="text-gray-500 text-sm">{b.phone}</div></div></div></div></div><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div></div>)
    if (templateId?.includes('bold')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-black/60" /><div className="absolute top-6 left-6 text-6xl font-black text-white">{headline}</div><div className="absolute bottom-0 left-0 right-0 p-8 text-white"><div className="text-5xl font-black mb-2" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div></div>)
    if (templateId?.includes('editorial')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'Georgia, serif' }}><div className="absolute inset-0 grid grid-cols-5"><div className="col-span-2 bg-gray-900 p-8 flex flex-col justify-between text-white"><div><div className="text-sm tracking-widest mb-4" style={{ color: pc }}>{headline}</div><div className="text-3xl font-light leading-tight mb-4">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div><div className="text-4xl font-light mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-4 pt-4 border-t border-white/20"><div>{b.business_name}</div><div className="text-white/60">{b.phone}</div></div></div></div><div className="col-span-3"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div></div></div>)
    if (templateId?.includes('glass')) return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute bottom-6 left-6 right-6 p-6 rounded-2xl text-white" style={{ backgroundColor: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(10px)' }}><div className="flex justify-between items-end"><div><div className="text-sm font-bold tracking-widest mb-2" style={{ color: pc }}>{headline}</div><div className="text-4xl font-bold mb-1">{formatPrice(p.price || 0)}</div><div className="text-xl">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div><div className="text-right"><div>{b.business_name} • {b.phone}</div></div></div></div></div>)

    // Default
    return (<div ref={ref} className="relative" style={{ width: 1200, height: 630, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/40 to-transparent" /><div className="absolute left-10 top-10 bottom-10 w-1/2 flex flex-col justify-between text-white"><div><div className="px-4 py-2 rounded-full inline-block mb-4" style={{ backgroundColor: pc }}><span className="font-bold" style={{ color: sc }}>{headline}</span></div><div className="text-5xl font-bold mb-2" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-semibold">{p.address}</div><div className="text-white/70">{p.city}, {p.state}</div></div><div><div className="flex gap-6 mb-4">{p.bedrooms} Beds • {p.bathrooms} Baths • {p.squareFeet?.toLocaleString()} Sq Ft</div><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-full flex items-center justify-center font-bold" style={{ backgroundColor: pc, color: sc }}>{b.business_name?.[0]}</div><div><div className="font-semibold">{b.business_name}</div><div className="text-white/60 text-sm">{b.phone}</div></div></div></div></div></div>)
  }
)
FacebookTemplateRenderer.displayName = 'FacebookTemplateRenderer'
