'use client'
import { forwardRef } from 'react'

interface PropertyData { address?: string; city?: string; state?: string; price?: number; bedrooms?: number; bathrooms?: number; squareFeet?: number }
interface BrandData { business_name?: string; logo_url?: string; primary_color?: string; secondary_color?: string; phone?: string }
interface Props { templateId: string; photoUrl: string; property: PropertyData; brand: BrandData; headline?: string }

function formatPrice(price: number): string {
  if (price >= 1000000) return `$${(price / 1000000).toFixed(price % 1000000 === 0 ? 0 : 1)}M`
  if (price >= 1000) return `$${(price / 1000).toFixed(0)}K`
  return `$${price.toLocaleString()}`
}

export const VerticalTemplateRenderer = forwardRef<HTMLDivElement, Props>(
  ({ templateId, photoUrl, property, brand, headline = 'JUST LISTED' }, ref) => {
    const pc = brand.primary_color || '#D4AF37'
    const sc = brand.secondary_color || '#1A1A1A'
    const p = property
    const b = brand
    const isCS = templateId?.includes('cs-')
    const isOH = templateId?.includes('oh-')
    const isPR = templateId?.includes('pr-')
    const isUC = templateId?.includes('uc-')
    const isJS = templateId?.includes('js-')

    if (isCS) {
      if (templateId?.includes('blur')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" style={{ filter: 'blur(20px)' }} crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-5xl mb-6">👀</div><div className="text-6xl font-bold mb-6">COMING SOON</div><div className="w-24 h-1 mb-8" style={{ backgroundColor: pc }} /><div className="text-2xl text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-5xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-12 px-8 py-4 rounded-full border-2" style={{ borderColor: pc }}><span className="text-xl">SWIPE UP</span></div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white"><div className="text-lg">{b.business_name}</div><div className="text-white/60">{b.phone}</div></div></div>)
      if (templateId?.includes('exclusive')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute top-20 right-8 px-6 py-3 rounded-full" style={{ backgroundColor: pc }}><span className="text-xl font-bold" style={{ color: sc }}>EXCLUSIVE</span></div><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-lg tracking-widest mb-4 text-white/60">PRIVATE PREVIEW</div><div className="text-5xl font-light mb-6">COMING SOON</div><div className="w-24 h-0.5 mb-6" style={{ backgroundColor: pc }} /><div className="text-2xl">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div><div className="text-5xl" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('countdown')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" style={{ filter: 'blur(10px) brightness(0.4)' }} crossOrigin="anonymous" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white p-12"><div className="text-2xl tracking-widest mb-8" style={{ color: pc }}>LAUNCHING SOON</div><div className="flex gap-4 mb-10">{['03','12','45','22'].map((n,i)=>(<div key={i} className="text-center"><div className="w-20 h-20 rounded-2xl flex items-center justify-center text-4xl font-bold" style={{backgroundColor:pc,color:sc}}>{n}</div><div className="text-sm mt-2 text-white/60">{['DAYS','HRS','MIN','SEC'][i]}</div></div>))}</div><div className="text-3xl font-bold mb-2">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="text-5xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('sneak')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><div className="absolute inset-x-0 top-0 h-1/2 bg-black flex items-end justify-center pb-10"><div className="text-white text-center"><div className="text-lg tracking-widest mb-4" style={{ color: pc }}>SNEAK PEEK</div><div className="text-5xl font-bold mb-4">COMING SOON</div><div className="text-white/70">{p.city}, {p.state}</div><div className="text-4xl font-bold mt-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div></div><div className="absolute inset-x-0 bottom-0 h-1/2"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div><div className="absolute bottom-8 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('dark')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui', backgroundColor: '#0a0a0a' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover opacity-20" style={{ filter: 'grayscale(100%)' }} crossOrigin="anonymous" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-9xl font-thin mb-8">?</div><div className="text-5xl font-bold tracking-wider mb-6">COMING SOON</div><div className="w-24 h-0.5 mb-6" style={{ backgroundColor: pc }} /><div className="text-white/50 text-xl">{p.city}, {p.state}</div><div className="text-4xl mt-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/40">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" style={{ filter: 'blur(8px)' }} crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/70 via-black/40 to-black/80" /><div className="absolute top-1/3 left-0 right-0 flex flex-col items-center text-white text-center p-12"><div className="w-24 h-24 rounded-full flex items-center justify-center mb-6" style={{ backgroundColor: pc }}><span className="text-5xl">🔔</span></div><div className="text-5xl font-bold mb-4">COMING SOON</div><div className="text-white/70 text-xl mb-6">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div><div className="px-8 py-4 rounded-full font-bold text-xl" style={{ backgroundColor: pc, color: sc }}>GET NOTIFIED</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
    }

    if (isOH) {
      if (templateId?.includes('invite')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-8 border border-white/30" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-lg tracking-widest mb-4 text-white/60">YOU ARE INVITED</div><div className="text-5xl font-light mb-6">OPEN HOUSE</div><div className="w-24 h-0.5 mb-8" style={{ backgroundColor: pc }} /><div className="text-5xl font-bold mb-4" style={{ color: pc }}>SAT & SUN</div><div className="text-2xl mb-8">1:00 PM - 4:00 PM</div><div className="text-2xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-3xl mt-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('calendar')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/90" /><div className="absolute top-20 left-1/2 transform -translate-x-1/2 w-40 bg-white rounded-2xl overflow-hidden shadow-2xl"><div className="py-3 text-center text-white text-xl font-bold" style={{ backgroundColor: pc }}>SAT</div><div className="py-6 text-center"><div className="text-6xl font-bold text-gray-900">15</div><div className="text-gray-500">1-4 PM</div></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-2xl font-bold tracking-wider mb-4" style={{ color: pc }}>OPEN HOUSE</div><div className="text-3xl font-bold mb-2">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-4xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('welcome')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/40 via-transparent to-black/90" /><div className="absolute top-20 left-0 right-0 text-center"><div className="inline-block px-8 py-4 rounded-full" style={{ backgroundColor: pc }}><span className="text-2xl font-bold" style={{ color: sc }}>🚪 OPEN HOUSE</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-5xl font-light mb-6">Welcome Home</div><div className="text-2xl mb-2">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="text-4xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-4 text-white/60">SAT & SUN • 1PM - 4PM</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('swipe')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black" /><div className="absolute top-20 left-0 right-0 text-center"><div className="text-3xl font-black text-white">🏠 OPEN HOUSE</div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-4xl font-bold mb-2" style={{ color: pc }}>SAT & SUN</div><div className="text-2xl mb-6">1:00 PM - 4:00 PM</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-4xl font-bold mb-8" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="px-8 py-4 rounded-full inline-block font-bold text-xl" style={{ backgroundColor: pc, color: sc }}>SWIPE UP ↑</div><div className="mt-8">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('luxury')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-8 border" style={{ borderColor: pc }} /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-lg tracking-widest mb-4" style={{ color: pc }}>EXCLUSIVE VIEWING</div><div className="text-5xl font-light mb-10">OPEN HOUSE</div><div className="text-4xl font-bold mb-2" style={{ color: pc }}>SAT 15 • 2-5 PM</div><div className="text-2xl mt-6">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div><div className="text-3xl mt-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/90" /><div className="absolute top-20 left-0 right-0 text-center"><div className="inline-block px-8 py-4 rounded-full" style={{ backgroundColor: pc }}><span className="text-2xl font-bold" style={{ color: sc }}>OPEN HOUSE</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-3xl font-bold mb-4">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state} • {formatPrice(p.price || 0)}</div><div className="px-8 py-4 rounded-full inline-block font-bold text-xl" style={{ backgroundColor: pc, color: sc }}>RSVP NOW</div><div className="mt-8">{b.business_name} • {b.phone}</div></div></div>)
    }

    if (isPR) {
      if (templateId?.includes('alert')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute top-20 left-0 right-0"><div className="mx-8 py-4 text-center" style={{ backgroundColor: '#DC2626' }}><span className="text-3xl font-bold text-white">🚨 PRICE DROP 🚨</span></div></div><div className="absolute inset-0 pt-40 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-2xl text-white/50 line-through mb-2">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-7xl font-black mb-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl mb-2">{p.address}</div><div className="text-white/70 mb-8">{p.city}, {p.state}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('savings')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/90" /><div className="absolute top-20 right-8 w-36 h-36 rounded-full flex flex-col items-center justify-center" style={{ backgroundColor: '#DC2626' }}><div className="text-white text-lg">SAVE</div><div className="text-white text-3xl font-black">{formatPrice((p.price || 0) * 0.1)}</div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-xl text-white/50 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-6xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('strike')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/70 via-transparent to-black/90" /><div className="absolute top-20 left-0 right-0 text-center"><div className="inline-block px-6 py-3" style={{ backgroundColor: '#DC2626' }}><span className="text-2xl font-bold text-white">🔥 PRICE REDUCED</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-2xl text-white/50 line-through mb-2">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-6xl font-bold mb-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('new')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><div className="absolute inset-x-0 top-0 h-1/2"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div><div className="absolute inset-x-0 bottom-0 h-1/2 bg-white p-10 flex flex-col justify-center text-center"><div className="flex items-center justify-center gap-3 mb-4"><span className="px-4 py-2 bg-green-500 text-white font-bold rounded-lg text-lg">NEW PRICE</span><span className="text-gray-400 line-through text-2xl">{formatPrice((p.price || 0) * 1.1)}</span></div><div className="text-6xl font-bold text-gray-900 mb-4">{formatPrice(p.price || 0)}</div><div className="text-2xl text-gray-700">{p.address}</div><div className="text-gray-500 mb-4">{p.city}, {p.state}</div><div className="flex items-center justify-center gap-3 mt-4"><div className="w-12 h-12 rounded-full flex items-center justify-center text-white font-bold text-xl" style={{ backgroundColor: pc }}>{b.business_name?.[0]}</div><div className="text-left"><div className="font-semibold text-gray-900 text-lg">{b.business_name}</div><div className="text-gray-500">{b.phone}</div></div></div></div></div>)
      if (templateId?.includes('opportunity')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-lg tracking-widest mb-4" style={{ color: pc }}>RARE OPPORTUNITY</div><div className="text-5xl font-light mb-8">PRICE IMPROVED</div><div className="text-2xl text-white/50 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-6xl font-light mb-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/90" /><div className="absolute top-20 left-0 right-0 text-center"><div className="inline-block px-6 py-3 rounded" style={{ backgroundColor: '#DC2626' }}><span className="text-2xl font-bold text-white">⚡ MOTIVATED SELLER</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-2xl text-white/40 line-through">{formatPrice((p.price || 0) * 1.1)}</div><div className="text-6xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
    }

    if (isUC) {
      if (templateId?.includes('pending')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/40" /><div className="absolute top-1/3 left-0 right-0"><div className="py-8 text-center" style={{ backgroundColor: pc }}><span className="text-5xl font-black" style={{ color: sc }}>📝 PENDING</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center bg-gradient-to-t from-black to-transparent"><div className="text-5xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl mb-2">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="text-lg">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('accepted')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-7xl mb-6">🎉</div><div className="text-5xl font-light mb-6">OFFER ACCEPTED</div><div className="w-24 h-0.5 mb-6" style={{ backgroundColor: pc }} /><div className="text-2xl">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div><div className="text-5xl" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('fast')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/70 via-transparent to-black/90" /><div className="absolute top-20 left-0 right-0 text-center"><div className="inline-block px-6 py-3 rounded-full" style={{ backgroundColor: '#DC2626' }}><span className="text-2xl font-bold text-white">⚡ MOVING FAST</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-5xl font-black mb-2">UNDER CONTRACT</div><div className="text-xl text-white/60 mb-6">IN JUST 3 DAYS!</div><div className="text-2xl">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-5xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-8">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('check')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute top-1/3 left-1/2 transform -translate-x-1/2 -translate-y-1/2"><div className="w-40 h-40 rounded-full flex items-center justify-center" style={{ backgroundColor: '#22C55E' }}><span className="text-8xl text-white">✓</span></div></div><div className="absolute top-20 left-0 right-0 text-center text-4xl font-bold text-white">UNDER CONTRACT</div><div className="absolute bottom-0 left-0 right-0 p-12 bg-gradient-to-t from-black to-transparent text-white text-center"><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70 mb-4">{p.city}, {p.state}</div><div className="text-4xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('signed')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-8 border" style={{ borderColor: pc }} /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-lg tracking-widest mb-4 text-white/60">CONTRACT</div><div className="text-6xl font-light mb-6">SIGNED</div><div className="w-24 h-0.5 mb-6" style={{ backgroundColor: pc }} /><div className="text-2xl">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div><div className="text-5xl" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/40 via-transparent to-black/90" /><div className="absolute top-20 left-0 right-0 text-center"><div className="inline-block px-8 py-4 rounded-full" style={{ backgroundColor: pc }}><span className="text-2xl font-bold" style={{ color: sc }}>🏠 BUYERS FOUND!</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-4xl font-bold mb-4">New Homeowners!</div><div className="text-2xl">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="text-5xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-8">{b.business_name} • {b.phone}</div></div></div>)
    }

    if (isJS) {
      if (templateId?.includes('sold') && !templateId?.includes('gold')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute top-1/3 left-1/2 transform -translate-x-1/2 -translate-y-1/2 -rotate-12"><div className="px-20 py-6" style={{ backgroundColor: '#DC2626' }}><span className="text-6xl font-black text-white">SOLD!</span></div></div><div className="absolute bottom-0 left-0 right-0 p-12 text-white text-center"><div className="text-4xl mb-2">🎉</div><div className="text-3xl font-bold mb-4">Congratulations!</div><div className="text-5xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl mb-2">{p.address}</div><div className="text-white/70 mb-8">{p.city}, {p.state}</div><div className="text-lg">{b.business_name} • {b.phone}</div></div></div>)
      if (templateId?.includes('celebrate')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-8xl mb-6">🎉</div><div className="text-6xl font-black mb-6">JUST SOLD!</div><div className="w-24 h-0.5 mb-6" style={{ backgroundColor: pc }} /><div className="text-2xl">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div><div className="text-5xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('gold')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute inset-8 border-2" style={{ borderColor: pc }} /><div className="absolute top-24 left-1/2 transform -translate-x-1/2"><div className="px-10 py-3 rounded-full" style={{ backgroundColor: pc }}><span className="text-2xl font-bold" style={{ color: sc }}>✨ SOLD ✨</span></div></div><div className="absolute inset-0 pt-40 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-4xl font-light mb-4">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div><div className="text-6xl font-light" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('achieve')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/70 via-transparent to-black/90" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-9xl mb-6">🏆</div><div className="text-3xl font-bold tracking-wider mb-2" style={{ color: pc }}>ANOTHER ONE</div><div className="text-6xl font-black mb-6">SOLD!</div><div className="text-2xl">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div><div className="text-5xl font-bold" style={{ color: pc }}>{formatPrice(p.price || 0)}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      if (templateId?.includes('record')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/60" /><div className="absolute top-20 left-0 right-0"><div className="mx-8 py-4 text-center" style={{ backgroundColor: '#DC2626' }}><span className="text-3xl font-bold text-white">🔥 RECORD SALE 🔥</span></div></div><div className="absolute inset-0 pt-40 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-5xl font-black mb-4">JUST SOLD</div><div className="text-6xl font-black mb-6" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)
      return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><div className="absolute inset-x-0 top-0 h-1/2"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div><div className="absolute inset-x-0 bottom-0 h-1/2 bg-white p-10 flex flex-col justify-center text-center"><div className="flex items-center justify-center gap-3 mb-4"><div className="px-4 py-2 rounded-lg font-bold text-white text-xl" style={{ backgroundColor: '#22C55E' }}>SOLD</div><div className="text-4xl font-bold text-gray-900">{formatPrice(p.price || 0)}</div></div><div className="text-2xl text-gray-700">{p.address}</div><div className="text-gray-500 mb-4">{p.city}, {p.state}</div><div className="flex items-center justify-center gap-3 mt-4"><div className="w-12 h-12 rounded-full flex items-center justify-center text-white font-bold text-xl" style={{ backgroundColor: pc }}>{b.business_name?.[0]}</div><div className="text-left"><div className="font-semibold text-gray-900 text-lg">{b.business_name}</div><div className="text-gray-500">{b.phone}</div></div></div></div></div>)
    }

    // JUST LISTED styles
    if (templateId?.includes('luxury')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/50" /><div className="absolute inset-8 border-2" style={{ borderColor: pc }} /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-xl tracking-widest mb-4" style={{ color: pc }}>{headline}</div><div className="text-6xl font-light mb-6">{formatPrice(p.price || 0)}</div><div className="w-24 h-0.5 mb-6" style={{ backgroundColor: pc }} /><div className="text-3xl">{p.address}</div><div className="text-white/60 mb-6">{p.city}, {p.state}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white/60">{b.business_name} • {b.phone}</div></div>)
    if (templateId?.includes('minimal')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><div className="absolute inset-x-0 top-0 h-1/2"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div><div className="absolute inset-x-0 bottom-0 h-1/2 bg-white p-10 flex flex-col justify-center text-center"><div className="text-sm tracking-widest mb-4" style={{ color: pc }}>{headline}</div><div className="text-5xl font-bold text-gray-900 mb-4">{formatPrice(p.price || 0)}</div><div className="text-2xl text-gray-700">{p.address}</div><div className="text-gray-500 mb-4">{p.city}, {p.state}</div><div className="flex items-center justify-center gap-3 mt-4"><div className="w-12 h-12 rounded-full flex items-center justify-center text-white font-bold text-xl" style={{ backgroundColor: pc }}>{b.business_name?.[0]}</div><div className="text-left"><div className="font-semibold text-gray-900 text-lg">{b.business_name}</div><div className="text-gray-500">{b.phone}</div></div></div></div></div>)
    if (templateId?.includes('bold')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/90" /><div className="absolute top-16 left-0 right-0 text-center text-6xl font-black text-white">{headline}</div><div className="absolute bottom-0 left-0 right-0 p-10 text-white text-center"><div className="text-6xl font-black mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-bold">{p.address}</div><div className="text-white/70 mb-6">{p.city}, {p.state}</div><div className="mt-6">{b.business_name} • {b.phone}</div></div></div>)
    if (templateId?.includes('editorial')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><div className="absolute inset-x-0 top-0 h-2/3"><img src={photoUrl} className="w-full h-full object-cover" crossOrigin="anonymous" /></div><div className="absolute inset-x-0 bottom-0 h-1/3 bg-gray-900 p-10 flex flex-col justify-center text-white text-center"><div className="text-sm tracking-widest mb-4" style={{ color: pc }}>{headline}</div><div className="text-3xl font-light mb-2">{p.address}</div><div className="text-white/60 mb-4">{p.city}, {p.state}</div><div className="text-5xl font-light" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="mt-4">{b.business_name} • {b.phone}</div></div></div>)
    if (templateId?.includes('elegant')) return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'Georgia, serif' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-black/40" /><div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center p-12"><div className="text-lg tracking-widest mb-4" style={{ color: pc }}>{headline}</div><div className="text-5xl font-light mb-6">{formatPrice(p.price || 0)}</div><div className="text-2xl">{p.address}</div><div className="text-white/60">{p.city}, {p.state}</div></div><div className="absolute bottom-20 left-0 right-0 text-center text-white">{b.business_name} • {b.phone}</div></div>)

    // Default
    return (<div ref={ref} className="relative" style={{ width: 1080, height: 1920, fontFamily: 'system-ui' }}><img src={photoUrl} className="absolute inset-0 w-full h-full object-cover" crossOrigin="anonymous" /><div className="absolute inset-0 bg-gradient-to-b from-black/60 via-transparent to-black/90" /><div className="absolute top-16 left-0 right-0 text-center"><div className="inline-block px-8 py-4 rounded-full" style={{ backgroundColor: pc }}><span className="text-2xl font-bold tracking-wider" style={{ color: sc }}>{headline}</span></div></div><div className="absolute bottom-0 left-0 right-0 p-10 text-white text-center"><div className="text-6xl font-bold mb-4" style={{ color: pc }}>{formatPrice(p.price || 0)}</div><div className="text-2xl font-semibold mb-2">{p.address}</div><div className="text-xl text-white/70 mb-6">{p.city}, {p.state}</div><div className="flex justify-center gap-8 mb-8 text-xl"><div className="text-center"><div className="text-3xl font-bold">{p.bedrooms}</div><div className="text-sm text-white/60">Beds</div></div><div className="text-center"><div className="text-3xl font-bold">{p.bathrooms}</div><div className="text-sm text-white/60">Baths</div></div><div className="text-center"><div className="text-3xl font-bold">{p.squareFeet?.toLocaleString()}</div><div className="text-sm text-white/60">Sq Ft</div></div></div><div className="flex items-center justify-center gap-3"><div className="w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold" style={{ backgroundColor: pc, color: sc }}>{b.business_name?.[0]}</div><div className="text-left"><div className="font-semibold">{b.business_name}</div><div className="text-white/60 text-sm">{b.phone}</div></div></div></div></div>)
  }
)
VerticalTemplateRenderer.displayName = 'VerticalTemplateRenderer'
